name: Run npm start

# This will supposedly provide more detailed debug information in the workflow execution logs.
env:
  ACTIONS_STEP_DEBUG: true

# https://stackoverflow.com/questions/68737385/how-to-trigger-github-actions-on-push-of-current-branch/68737519#68737519
on: [push]

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run npm start and write terminal output to `npmStartOutput.txt`.
        # https://stackoverflow.com/questions/57915432/write-output-of-npm-run-start-to-a-file/57920886#57920886
        run: npm start 2>&1| tee npmStartOutput.txt
        continue-on-error: true
        id: npm-start

      - name: List files in the current directory
        run: ls -a

      - name: Print working directory
        run: pwd

      - name: Print the output of the previous step
        run: echo "${{ steps.npm-start.outputs.stdout }}"

      - name: Upload npmStartOutput.txt as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: npmStartOutput
          path: npmStartOutput.txt

  comment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download npmStartOutput artifact
        uses: actions/download-artifact@v2
        with:
          name: npmStartOutput
          path: output

      - name: Create comment with npm start output
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('output/npmStartOutput.txt', 'utf8');
            const commentBody = `**\`npm start\` output**:\n\`\`\`\n${output}\n\`\`\``;

            github.rest.repos.createCommitComment({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
